# Generated by Django 3.2 on 2023-10-09 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recording',
            name='audio_data',
        ),
        migrations.RemoveField(
            model_name='recording',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='recording',
            name='user',
        ),
        migrations.AddField(
            model_name='recording',
            name='correct_pronunciation',
            field=models.CharField(default=5, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recording',
            name='word',
            field=models.CharField(default=10, max_length=100),
            preserve_default=False,
        ),
    ]
